<?php

namespace Database\Seeders;

use App\Models\Equipement;
use App\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EquipementSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $services = Service::all()->keyBy('code');

        $equipements = [
            // === RADIOLOGIE ===
            [
                'nom' => 'Scanner CT',
                'code_inventaire' => 'SCAN-CT-001',
                'numero_serie' => 'SN-CT-123456',
                'marque' => 'Siemens',
                'modele' => 'Somatom Go',
                'service_id' => $services['RAD']->id,
                'localisation' => 'Salle Scanner 1',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-01-15',
                'fournisseur' => 'Siemens Healthineers',
            ],
            [
                'nom' => 'IRM',
                'code_inventaire' => 'IRM-001',
                'numero_serie' => 'SN-IRM-789012',
                'marque' => 'GE Healthcare',
                'modele' => 'SIGNA Artist',
                'service_id' => $services['RAD']->id,
                'localisation' => 'Salle IRM 2',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2021-06-20',
                'fournisseur' => 'GE Healthcare',
            ],
            [
                'nom' => 'Échographe',
                'code_inventaire' => 'ECHO-001',
                'numero_serie' => 'SN-ECHO-445566',
                'marque' => 'Philips',
                'modele' => 'EPIQ Elite',
                'service_id' => $services['RAD']->id,
                'localisation' => 'Salle Écho 3',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-04-10',
                'fournisseur' => 'Philips Healthcare',
            ],
            [
                'nom' => 'Mammographe',
                'code_inventaire' => 'MAMMO-001',
                'numero_serie' => 'SN-MAM-778899',
                'marque' => 'Hologic',
                'modele' => 'Dimensions 3D',
                'service_id' => $services['RAD']->id,
                'localisation' => 'Salle Mammographie',
                'criticite' => 'haute',
                'statut' => 'en_maintenance',
                'date_mise_en_service' => '2020-11-05',
                'fournisseur' => 'Hologic',
            ],
            [
                'nom' => 'Radiographe numérique',
                'code_inventaire' => 'RX-001',
                'numero_serie' => 'SN-RX-334455',
                'marque' => 'Agfa',
                'modele' => 'DR 600',
                'service_id' => $services['RAD']->id,
                'localisation' => 'Salle RX',
                'criticite' => 'moyenne',
                'statut' => 'en_service',
                'date_mise_en_service' => '2019-08-15',
                'fournisseur' => 'Agfa Healthcare',
            ],

            // === BLOC OPERATOIRE ===
            [
                'nom' => 'Table opératoire électrique',
                'code_inventaire' => 'TABLE-OP-001',
                'numero_serie' => 'SN-TOP-345678',
                'marque' => 'Maquet',
                'modele' => 'Magnus',
                'service_id' => $services['BLOC']->id,
                'localisation' => 'Bloc 1',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2020-03-10',
                'fournisseur' => 'Getinge',
            ],
            [
                'nom' => 'Respirateur artificiel',
                'code_inventaire' => 'RESP-001',
                'numero_serie' => 'SN-RESP-901234',
                'marque' => 'Hamilton',
                'modele' => 'C6',
                'service_id' => $services['BLOC']->id,
                'localisation' => 'Bloc 2',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-02-28',
                'fournisseur' => 'Hamilton Medical',
            ],
            [
                'nom' => 'Bistouri électrique',
                'code_inventaire' => 'BIST-001',
                'numero_serie' => 'SN-BIST-112233',
                'marque' => 'Erbe',
                'modele' => 'VIO 300D',
                'service_id' => $services['BLOC']->id,
                'localisation' => 'Bloc 3',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2021-05-20',
                'fournisseur' => 'Erbe',
            ],
            [
                'nom' => 'Lampe scialytique',
                'code_inventaire' => 'LAMPE-001',
                'numero_serie' => 'SN-LAMP-998877',
                'marque' => 'TRILUX',
                'modele' => 'Surgical LED',
                'service_id' => $services['BLOC']->id,
                'localisation' => 'Bloc 1',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-09-12',
                'fournisseur' => 'TRILUX Medical',
            ],

            // === HEMODIALYSE ===
            [
                'nom' => 'Générateur hémodialyse',
                'code_inventaire' => 'GEN-HEMO-001',
                'numero_serie' => 'SN-GH-567890',
                'marque' => 'Fresenius',
                'modele' => '5008',
                'service_id' => $services['HEMO']->id,
                'localisation' => 'Box 1',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-09-05',
                'fournisseur' => 'Fresenius Medical Care',
            ],
            [
                'nom' => 'Générateur hémodialyse 2',
                'code_inventaire' => 'GEN-HEMO-002',
                'numero_serie' => 'SN-GH-667891',
                'marque' => 'Fresenius',
                'modele' => '5008',
                'service_id' => $services['HEMO']->id,
                'localisation' => 'Box 2',
                'criticite' => 'haute',
                'statut' => 'en_panne',
                'date_mise_en_service' => '2022-09-05',
                'fournisseur' => 'Fresenius Medical Care',
            ],
            [
                'nom' => 'Moniteur patient multiparamètres',
                'code_inventaire' => 'MONI-HEMO-001',
                'numero_serie' => 'SN-MON-445522',
                'marque' => 'Philips',
                'modele' => 'IntelliVue MX450',
                'service_id' => $services['HEMO']->id,
                'localisation' => 'Salle surveillée',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-01-15',
                'fournisseur' => 'Philips Healthcare',
            ],

            // === URGENCES ===
            [
                'nom' => 'Défibrillateur',
                'code_inventaire' => 'DEFIB-001',
                'numero_serie' => 'SN-DEF-112233',
                'marque' => 'Zoll',
                'modele' => 'X Series',
                'service_id' => $services['URG']->id,
                'localisation' => 'Box Urgences 3',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-11-12',
                'fournisseur' => 'Zoll Medical',
            ],
            [
                'nom' => 'Moniteur multiparamètres',
                'code_inventaire' => 'MONI-URG-001',
                'numero_serie' => 'SN-MU-445566',
                'marque' => 'GE Healthcare',
                'modele' => ' CARESCAPE B450',
                'service_id' => $services['URG']->id,
                'localisation' => 'Box Urgences 1',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-07-20',
                'fournisseur' => 'GE Healthcare',
            ],
            [
                'nom' => 'Aspirateur chirurgical',
                'code_inventaire' => 'ASPI-URG-001',
                'numero_serie' => 'SN-AS-998877',
                'marque' => 'Medela',
                'modele' => 'Dominant Flex',
                'service_id' => $services['URG']->id,
                'localisation' => 'Box Urgences 2',
                'criticite' => 'moyenne',
                'statut' => 'en_service',
                'date_mise_en_service' => '2021-03-18',
                'fournisseur' => 'Medela',
            ],

            // === CARDIOLOGIE ===
            [
                'nom' => 'Appareil ECG',
                'code_inventaire' => 'ECG-001',
                'numero_serie' => 'SN-ECG-223344',
                'marque' => 'Schiller',
                'modele' => 'AT-10 Plus',
                'service_id' => $services['CARD']->id,
                'localisation' => 'Salle Examen Cardio',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-04-22',
                'fournisseur' => 'Schiller',
            ],
            [
                'nom' => 'Holter ECG',
                'code_inventaire' => 'HOLTER-001',
                'numero_serie' => 'SN-HLT-556677',
                'marque' => 'GE Healthcare',
                'modele' => 'SEER 12',
                'service_id' => $services['CARD']->id,
                'localisation' => 'Salle Holter',
                'criticite' => 'moyenne',
                'statut' => 'en_service',
                'date_mise_en_service' => '2021-08-30',
                'fournisseur' => 'GE Healthcare',
            ],

            // === REANIMATION ===
            [
                'nom' => 'Ventilateur mécanique',
                'code_inventaire' => 'VENT-001',
                'numero_serie' => 'SN-VENT-334422',
                'marque' => 'Dräger',
                'modele' => 'Evita V500',
                'service_id' => $services['REA']->id,
                'localisation' => 'Chambre Réa 1',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-05-10',
                'fournisseur' => 'Dräger Medical',
            ],
            [
                'nom' => 'Pompe à perfusion',
                'code_inventaire' => 'POMPE-001',
                'numero_serie' => 'SN-PMP-889900',
                'marque' => 'B. Braun',
                'modele' => 'Space',
                'service_id' => $services['REA']->id,
                'localisation' => 'Chambre Réa 2',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-11-15',
                'fournisseur' => 'B. Braun',
            ],

            // === LABORATOIRE ===
            [
                'nom' => 'Analyseur biochimie',
                'code_inventaire' => 'ANAL-BIO-001',
                'numero_serie' => 'SN-AB-112244',
                'marque' => 'Roche',
                'modele' => 'cobas c 503',
                'service_id' => $services['LABO']->id,
                'localisation' => 'Labo Biochimie',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2021-02-10',
                'fournisseur' => 'Roche Diagnostics',
            ],
            [
                'nom' => 'Analyseur hématologie',
                'code_inventaire' => 'ANAL-HEM-001',
                'numero_serie' => 'SN-AH-556611',
                'marque' => 'Sysmex',
                'modele' => 'XN-1000',
                'service_id' => $services['LABO']->id,
                'localisation' => 'Labo Hématologie',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2020-09-05',
                'fournisseur' => 'Sysmex',
            ],
            [
                'nom' => 'Centrifugeuse',
                'code_inventaire' => 'CENTRI-001',
                'numero_serie' => 'SN-CEN-778833',
                'marque' => 'Eppendorf',
                'modele' => '5810 R',
                'service_id' => $services['LABO']->id,
                'localisation' => 'Labo Pré-analytique',
                'criticite' => 'moyenne',
                'statut' => 'en_maintenance',
                'date_mise_en_service' => '2019-06-20',
                'fournisseur' => 'Eppendorf',
            ],

            // === MATERNITE ===
            [
                'nom' => 'Cardiotocographe',
                'code_inventaire' => 'CTG-001',
                'numero_serie' => 'SN-CTG-334411',
                'marque' => 'Philips',
                'modele' => 'Avalon FM50',
                'service_id' => $services['MAT']->id,
                'localisation' => 'Salle Accouchement 1',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-03-08',
                'fournisseur' => 'Philips Healthcare',
            ],
            [
                'nom' => 'Berceau radiant',
                'code_inventaire' => 'BERCEAU-001',
                'numero_serie' => 'SN-BR-998833',
                'marque' => 'Dräger',
                'modele' => 'Babytherm 8004',
                'service_id' => $services['MAT']->id,
                'localisation' => 'Salle Néonatologie',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-01-20',
                'fournisseur' => 'Dräger Medical',
            ],

            // === PEDIATRIE ===
            [
                'nom' => 'Incubateur néonatal',
                'code_inventaire' => 'INCUB-001',
                'numero_serie' => 'SN-INC-223311',
                'marque' => 'GE Healthcare',
                'modele' => 'Giraffe OmniBed',
                'service_id' => $services['PED']->id,
                'localisation' => 'Chambre Prématurés',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-06-15',
                'fournisseur' => 'GE Healthcare',
            ],

            // === STERILISATION ===
            [
                'nom' => 'Autoclave',
                'code_inventaire' => 'AUTO-001',
                'numero_serie' => 'SN-AUT-556622',
                'marque' => 'Getinge',
                'modele' => 'HS6610',
                'service_id' => $services['STE']->id,
                'localisation' => 'Zone Stérilisation',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2021-04-12',
                'fournisseur' => 'Getinge',
            ],
            [
                'nom' => 'Laveur désinfecteur',
                'code_inventaire' => 'LAVE-001',
                'numero_serie' => 'SN-LV-998844',
                'marque' => 'Miele',
                'modele' => 'PG 8583',
                'service_id' => $services['STE']->id,
                'localisation' => 'Zone Lavage',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2020-10-05',
                'fournisseur' => 'Miele Professional',
            ],

            // === ONCOLOGIE ===
            [
                'nom' => 'Accélérateur linéaire',
                'code_inventaire' => 'LINAC-001',
                'numero_serie' => 'SN-LIN-667733',
                'marque' => 'Varian',
                'modele' => 'TrueBeam',
                'service_id' => $services['ONCO']->id,
                'localisation' => 'Bunker Radiothérapie',
                'criticite' => 'critique',
                'statut' => 'en_service',
                'date_mise_en_service' => '2022-08-01',
                'fournisseur' => 'Varian Medical',
            ],

            // === PHARMACIE ===
            [
                'nom' => 'Automate de préparation',
                'code_inventaire' => 'AUTO-PHAR-001',
                'numero_serie' => 'SN-APH-445577',
                'marque' => 'BD',
                'modele' => 'Rowa Vmax',
                'service_id' => $services['PHAR']->id,
                'localisation' => 'Pharmacie centrale',
                'criticite' => 'moyenne',
                'statut' => 'en_service',
                'date_mise_en_service' => '2021-12-18',
                'fournisseur' => 'BD',
            ],
            [
                'nom' => 'Réfrigérateur pharmaceutique',
                'code_inventaire' => 'FRIGO-PHAR-001',
                'numero_serie' => 'SN-FR-112255',
                'marque' => 'Liebherr',
                'modele' => 'MKv 3910',
                'service_id' => $services['PHAR']->id,
                'localisation' => 'Pharmacie Stock',
                'criticite' => 'haute',
                'statut' => 'en_service',
                'date_mise_en_service' => '2023-02-28',
                'fournisseur' => 'Liebherr',
            ],
        ];

        foreach ($equipements as $data) {
            Equipement::firstOrCreate(
                ['code_inventaire' => $data['code_inventaire']],
                $data
            );
        }
    }
}
